<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>metal</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Metal Shader</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#properties_functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#struct-definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-definition</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.block.metal</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.metal</string>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.metal</string>
					<key>match</key>
					<string>\b([0-9]+\.?[0-9]*)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.metal</string>
					<key>match</key>
					<string>\b(\.[0-9]+)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex.metal</string>
					<key>match</key>
					<string>\b(0x[0-9A-F]+)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.metal</string>
					<key>match</key>
					<string>\b(false|true)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.metal</string>
					<key>match</key>
					<string>\b(break|case|continue|default|discard|do|else|for|if|return|switch|while)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.metal</string>
					<key>match</key>
					<string>\b(kernel|vertex|fragment|static)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.typealias.metal</string>
					<key>match</key>
					<string>\b(typedef)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(#include|#import)\s(&lt;.*&gt;|".*")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.include.metal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.metal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(#if|#endif)\s*(\w*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.metal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.metal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(using)\s(namespace)\s(.*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.using.metal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.namespace.metal</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.namespace.metal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\w+)\:\:(\w+)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.metal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.metal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((?:\w|\&lt;|\&gt;|\s)+)\s+(?:\**|&amp;*)\s*(\w+)\s*=?\s*((?:\w|\.|\[|\]|\(|\)|\{|\})+);</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
								<dict>
									<key>name</key>
									<string>keyword.control.metal</string>
									<key>match</key>
									<string>\b(return)\b</string>
								</dict>
								<dict>
									<key>name</key>
									<string>entity.name.type.metal</string>
									<key>match</key>
									<string>\b(\w+)\b</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#properties_functions</string>
								</dict>
							</array>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.metal</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<key>struct-definition</key>
		<dict>
			<key>begin</key>
			<string>\b(struct)\s*(\w*)\s*({*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.strutured.metal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.metal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.begin-struct-definition.metal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})\s*(\w*);</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.end-struct-definition.metal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.metal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.type.metal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?:\w|\&lt;|\&gt;|,|\s|\*)+)(?:\**|&amp;*)\s+(?:\**|&amp;*)(\w+)\[*\w*\]*\s*(?:\[\[\s*(\w+)\(*(\w*)\)*\s*\]\])*;</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
								<dict>
									<key>name</key>
									<string>entity.name.type.metal</string>
									<key>match</key>
									<string>\b(\w+)\b</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.metal</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.metal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.variable.metal</string>
				</dict>
			</array>
		</dict>
		<key>function-definition</key>
		<dict>
			<key>begin</key>
			<string>\b((?:\w|\&lt;|\&gt;|,|\s)+)\s+(\w+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#types</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.type.metal</string>
							<key>match</key>
							<string>\b(\w+)\b</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.metal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.begin-function-definition.metal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\{)|;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.end-function-definition.metal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.metal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?:\w|\&lt;|\&gt;|,|\s|\:)+)(?:\**|&amp;*)\s+(?:\**|&amp;*)(\w+)\s*(?:\[\[\s*(\w+)\(*(\w*)\)*\s*\]\])*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#types</string>
								</dict>
								<dict>
									<key>name</key>
									<string>entity.name.type.metal</string>
									<key>match</key>
									<string>\b(\w+)\b</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.metal</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.metal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.variable.parameter.metal</string>
				</dict>
			</array>
		</dict>
		<key>properties_functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?:\w|\[|\])+)\.(\w+)\(</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.metal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>((?:\w|\[|\])+)\s*\(</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.metal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>((?:\w|\[|\])+)\.(\w+)\.(\w+)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.metal</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.metal</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>((?:\w|\[|\])+)\.(\w+)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.metal</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.modifier.metal</string>
					<key>match</key>
					<string>\b(const|constant|device|constexpr)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.metal</string>
					<key>match</key>
					<string>\b(vertex_id|instance_id|draw_id|stage_in)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(float4x4)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(bool(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(char(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(short(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(int(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(long(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(uchar(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(ushort(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(uint(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(ulong(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(half(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(float(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(vector_float(?:2|3|4*))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(texture(?:2|3|4*)d)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(array)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(sampler)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.scalar.metal</string>
					<key>match</key>
					<string>\b(void)\b</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.metal</string>
	<key>uuid</key>
	<string>A1B2C3D4-E5F6-7890-1234-567890ABCDEF</string>
</dict>
</plist>
